# Discovery of notebooks

This is some Markdown code with *italics* and _bold_ with underscores.

### Title

You can also write math: $$\exp(i \pi) + 1 = 0$$

Can also use code with backticks: 
```python
x = 1
```

In [1]:
x = 2  # comment: notice the space around the equal (PEP8)
print(x)

2


In [2]:
# check your python version
import sys
print(sys.version)

3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:32:50) [Clang 16.0.6 ]


In [3]:
!python --version

Python 3.12.5


In [4]:
!pwd  # can run bash commands inside python cell using `!`

/Users/sylvaincom/Documents/GitHub/pyds_lectures/cs_exed/ms_ia_confiance/2024_2025/lectures


In [5]:
!pip install numpy

# Declaring variables

In [6]:
y = 3
y  # will print the variable if it is at the last line

3

In [7]:
1
2 # only the value gets displayed

2

In [8]:
print(1)
print(2)

1
2


In [9]:
print(3 + 2)

5


In [10]:
x = 3+2
print(x)

5


In [11]:
print(type(x))

<class 'int'>


In [12]:
help(type)

Help on class type in module builtins:

class type(object)
 |  type(object) -> the object's type
 |  type(name, bases, dict, **kwds) -> a new type
 |
 |  Methods defined here:
 |
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |
 |  __dir__(self, /)
 |      Specialized __dir__ implementation for types.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __instancecheck__(self, instance, /)
 |      Check if an object is an instance.
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __setattr__(self, name, value, /)
 |      Implement setattr(self, name, value).
 |
 |  __sizeof__(self, /)
 |      Return memory consumption of the t

In [13]:
my_variable = 1  # snake_case: everything in lower case, separated by underscores 
MyClass = 0  # CamelCase: avoid, only for classes
_my_variable = 0 # this means "private", use at your own risks
my_variable2 = 0

In [14]:
2_variable  # cannot start with a digit

SyntaxError: invalid decimal literal (3026941591.py, line 1)

In [15]:
age = 30  # use meaningful variable names

In [16]:
my_very_long_variable_name = 31

In [17]:
my_very_long_variable_name # use autocomplete (Tab)

31

In [18]:
type(age)

int

In [19]:
n = 1000000 # not nice
print(n, type(n))
n = 10*6 # nice
print(n, type(n))
n = 1e6 # nice, but float
print(n, type(n))
n = 1_000_000 # very nice (for readability)
print(n, type(n))

1000000 <class 'int'>
60 <class 'int'>
1000000.0 <class 'float'>
1000000 <class 'int'>


In [20]:
n = 236617 # not nice
print(n)
n = 236_617 # very nice
print(n)

236617
236617


In [21]:
x = 1
print(x)

x += 1  # x = x + 1
print(x)

x -= 3 # x = x - 3
print(x)

x *= 12 # x = x * 12
print(x)

x /= 3 # x = x / 3
print(x)

1
2
-1
-12
-4.0


# For-loops

In [22]:
n = 5
for i in range(n):
    print(i)

0
1
2
3
4


In [23]:
n = 5
for i in range(n+1):
    print(i)

0
1
2
3
4
5


In [24]:
n = 5
for i in range(1, n+1):
    print(i)

1
2
3
4
5


In [25]:
n = 10
for i in range(0, n+1, 2):
    print(i)

0
2
4
6
8
10


In [26]:
for _ in range(5): # _ means that it will be discarded, not useful
    print(2)

2
2
2
2
2


In [27]:
my_sum = 0
for i in range(5): # use `i` if it is reused, a true variable
    my_sum += i

# Manipulating strings

In [28]:
first_name = "John"
last_name = 'Doe'  # single quotes also work

In [29]:
type(first_name)

str

In [30]:
print(first_name)
print(first_name, last_name)

John
John Doe


In [31]:
# you should use f-strings (format strings)
print(f"My first name is {first_name} and my last name is {last_name}") 
# instead of:
print("My first name is", first_name, "and my last name is", last_name)
# f-strings can be very concise:
print(f"{first_name = }")

My first name is John and my last name is Doe
My first name is John and my last name is Doe
first_name = 'John'


In [32]:
s = "line1\nline2"
print(s)

line1
line2


In [33]:
s = "word1\tword2"
print(s)

word1	word2


In [34]:
s = "word1\n\tword2"
print(s)

word1
	word2


In [35]:
len(first_name)

4

In [36]:
first_name[0]  # python indexes always start at 0

'J'

In [37]:
first_name[1]

'o'

In [38]:
first_name[len(first_name)]

IndexError: string index out of range

get used to reading python errors because they are very informative, always start from the bottom of the message error, copy-paste the last line on Google to understand what is going on

In [39]:
first_name[len(first_name)-1]

'n'

In [40]:
first_name[-1]  # most commonly used to get the last element of a sequence

'n'

In [41]:
first_name[-2]  # - 2 is interpreted as len(first_name) - 2

'h'

In [42]:
first_name[2:4]  # this is called slicing

'hn'

In [43]:
print(first_name)
print(first_name[1:5:2])  # first:last:step means from first incl. to last excl. by steps of `steps`

John
on


In [44]:
print(first_name[:5:2])  # nothing means 0 for first
print(first_name[2::2])  # nothing means len(first_name) for last
print(first_name[::2])

Jh
h
Jh


In [45]:
print(first_name[::-1])  # this is the most commonly used to reverse a string
print(first_name[-3:1:1])  # if first is greater than last and step is >0, we get empty string
print(len(first_name[-3:1:1]))
print(first_name[-3:1:-1])

nhoJ

0



In [46]:
for char in first_name:
    print(char)

J
o
h
n


In [47]:
for i in range(len(first_name)):
    print(first_name[i])

J
o
h
n


In [48]:
first_name.lower()
# this "lower" function is called a method and it's
# "attached" to the variable `first_name`

'john'

In [49]:
lower(first_name)  # does not work, not defined

NameError: name 'lower' is not defined

# Manipulating the types

In [50]:
my_num = 123
my_num[0]

TypeError: 'int' object is not subscriptable

In [51]:
x = 1.
y = 0. 
print(x, y)

# swap x and y 
x, y = y, x  # those are called tuples, you can also write (x, y)  
print(x, y)

1.0 0.0
0.0 1.0


In [52]:
my_int = 1
print(type(my_int))
my_float = 1.5 
print(type(my_float))
my_second_float = 1.
print(type(my_second_float))

<class 'int'>
<class 'float'>
<class 'float'>


In [53]:
type(float(my_int))

float

In [54]:
type(int(my_float))

int

In [55]:
int(1.8)  # this take the ceil function of its argument

1

In [56]:
"123" + 1

TypeError: can only concatenate str (not "int") to str

In [57]:
int("123") + 1

124

In [58]:
int("12a")

ValueError: invalid literal for int() with base 10: '12a'

In [59]:
"123" + "345"  # this does concatenation

'123345'

In [60]:
[0, 1, 3] + [3, 4, -1]  # also concatenation for lists, and tuples

[0, 1, 3, 3, 4, -1]

same `+` operation, but it adapts to the types and does something different

In [61]:
"123" * 3

'123123123'

In [62]:
[0] * 3

[0, 0, 0]

In [63]:
print("#" * 80)  # do *not* write `print("#################")`

################################################################################


In [64]:
len("123")

3

In [65]:
len(123)

TypeError: object of type 'int' has no len()

In [66]:
2.5 + 1

3.5

In [67]:
1 / 2

0.5

In [68]:
print(3 // 2)  # this is integer div
# same as 
print(int(3 / 2))

1
1


In [69]:
2 / 3

0.6666666666666666

Python is the best calculator, do not use the calculator of your smartphone when you have python in front of you...

In [70]:
round(4.5)

4

In [71]:
round(3.5139879, 3)  # pass a second argument 

3.514

In [72]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [73]:
# how to check if a number is even or uneven?

x = 10
print(x%2)  # rest of the Euclidean division

0


In [74]:
x = 11
if x%2 == 0:
    print(f"{x = } is even")
else:
    print(f"{x = } is uneven")

x = 11 is uneven


# Manipulating booleans and if-else conditions

In [75]:
# comparing objects
1 == 2

False

In [76]:
1 != 2

True

In [77]:
type(1)

int

In [78]:
type(1.0)

float

In [79]:
1 == 1.0  # this compares the object values

True

In [80]:
if True:
    print("1st answer")

1st answer


In [81]:
if False:
    print("1st answer")
print("without indent, it is not in the condition")

without indent, it is not in the condition


In [82]:
if False:
    print("1st answer")

In [83]:
x = 2
if x == 2:
    print("1st answer")

1st answer


In [84]:
y = 3
if y == 2:
    print("1st answer")
else:
    print("2nd answer")

2nd answer


In [85]:
1 < 2

True

In [86]:
"a" < "z"

True

In [87]:
"abc" < "abe"

True

# Manipulating lists

In [88]:
my_list = ['a', 'b', 'c', 'd']
type(my_list)

list

In [89]:
my_list

['a', 'b', 'c', 'd']

In [90]:
len(my_list)

4

In [91]:
for i in range(len(my_list)):
    print(i)

0
1
2
3


In [92]:
min([0, 1, -1])

-1

In [93]:
max(["a", 'z', "A"])  # upper case comes first in lexicographic order

'z'

In [94]:
sum([0, 1, -1])

0

In [95]:
list("John")  # from string to list

['J', 'o', 'h', 'n']

In [96]:
# from list to string
"".join(["J", "o", "h", "n"])  # this is the "joining" operation

'John'

In [97]:
"_".join(["J", "o", "h", "n"])

'J_o_h_n'

In [98]:
sorted(["a", 'z', "A"])  # using the builtin `sorted` function

['A', 'a', 'z']

In [99]:
for i in range(len(my_list)):
    print(my_list[i])

a
b
c
d


In [100]:
for elem in my_list:
    print(elem)

a
b
c
d


In [101]:
my_list = [1, "a", 2.1]  # each element can be of different type

In [102]:
my_list_1 = [1, "a", 2.1]
my_list_2 = [-1, "b"]
my_list_1 + my_list_2  # concatenate lists

[1, 'a', 2.1, -1, 'b']

In [103]:
my_list = [18, 17, 20]

In [104]:
my_list[-1]

20

In [105]:
my_list.append(10)
my_list

[18, 17, 20, 10]

In [106]:
my_list[-1]

10

In [107]:
# list in comprehension
my_list = [i for i in range(5)]
my_list

[0, 1, 2, 3, 4]

In [108]:
my_list = [i+1 for i in range(5)]
my_list

[1, 2, 3, 4, 5]

In [109]:
my_list = [i**2 for i in range(5)]
my_list

[0, 1, 4, 9, 16]

In [110]:
my_list = [i for i in range(10) if True]
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
my_list = [i for i in range(10) if False]
my_list

[]

In [112]:
my_list = [i for i in range(10) if i%2 == 0]
my_list

[0, 2, 4, 6, 8]

In [113]:
my_list = [i**2 for i in range(10) if i%2 == 0]
my_list

[0, 4, 16, 36, 64]

# Manipulating dictionaries

In [114]:
my_dict = dict() # or {}
my_dict["matthieu"] = 18
my_dict["valentine"] = 17
my_dict["yanis"] = 20
print(my_dict)
print(my_dict["yanis"])

{'matthieu': 18, 'valentine': 17, 'yanis': 20}
20


In [115]:
my_dict["elise"] = 10
print(my_dict)

{'matthieu': 18, 'valentine': 17, 'yanis': 20, 'elise': 10}


contrary to lists, in dictionaries, you access the value using a key and not an index

In [116]:
for (key, value) in my_dict.items():
    print(key, value)

matthieu 18
valentine 17
yanis 20
elise 10


# Manipulating numpy arrays

In [117]:
import numpy as np

In [118]:
M = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)
M  # use `M` in capital letters instead of `m` because it is an array and not an integer or vector

array([[1, 2, 3],
       [4, 5, 6]])

an array if a list of lists

In [119]:
type(M)

numpy.ndarray

In [120]:
 # always know the shapes of your arrays
print(np.shape(M))
print(M.shape)

(2, 3)
(2, 3)


In [121]:
my_list_of_lists = [
    [1, 2, 3],
    [4, 5, 6]
]
my_list_of_lists

[[1, 2, 3], [4, 5, 6]]

In [122]:
np.array(my_list_of_lists)

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
N = np.array(
    [[1, 2, 3],
     [4, "b", 6]]
)
N # all elements must have the same type, contrary to lists

array([['1', '2', '3'],
       ['4', 'b', '6']], dtype='<U21')

In [124]:
my_irregular_list = [
    [1, 2, 3],
    [4, 5]
]
print(my_irregular_list)

[[1, 2, 3], [4, 5]]


In arrays, each row must have the same number of columns

In [125]:
print(np.array(my_irregular_list))


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [126]:
M = np.ones(5)
M

array([1., 1., 1., 1., 1.])

In [127]:
M = np.ones((3, 5))
M

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [128]:
M = np.zeros((5, 3))
M

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [129]:
M = np.eye(3)
M

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
np.diag(M)

array([1., 1., 1.])

In [131]:
M = np.array([[1, 0], [0, 1]])
N = np.array([[4, 1], [2, 2]])
print(M)
print(N)
print(M+N)

[[1 0]
 [0 1]]
[[4 1]
 [2 2]]
[[5 1]
 [2 3]]


In [132]:
print(np.dot(M, N))

[[4 1]
 [2 2]]


# Functions

In [133]:
# a function always returns something  
output = print(1)

1


In [134]:
print(output)
print(type(output))

None
<class 'NoneType'>


In [135]:
# None is the python object to mean: nothing
output is None  # notice the "is" keyword for (identity) object comparison

True

## Several inputs (arguments) or several outputs

In [136]:
def my_func(x):
    output = 2*x
    output = output+1
    return output

my_func(1)

3

In [137]:
# more concise
def my_func(x):
    return 2*x+1

my_func(1)

3

In [138]:
# a function transforms an input and returns an output
intput = 1
output = my_func(intput)
output

3

In [139]:
# several outputs
def my_func(x):
    y = x+1
    z = x+2
    return y, z

y, z = my_func(1)
print(y, z)

2 3


In [140]:
# can return choose to return a dictionary with the outputs
def my_func(x):
    d = dict()
    d["first_out"] = x+1
    d["second_out"] = x+2
    return d

d = my_func(2)
print(d)

{'first_out': 3, 'second_out': 4}


In [141]:
# several inputs
def my_func(first_arg, second_arg):
    print(f"{first_arg = }\n{second_arg = }")

my_func(1, "CS")

first_arg = 1
second_arg = 'CS'


## About the arguments of a function

In [142]:
def my_func(first_arg, second_arg):
    print(f"{first_arg = }\n{second_arg = }")

In [143]:
my_func(1, "CS")

first_arg = 1
second_arg = 'CS'


In [144]:
my_func(second_arg=1, first_arg="CS")

first_arg = 'CS'
second_arg = 1


In [145]:
my_func(second_arg=2)

TypeError: my_func() missing 1 required positional argument: 'first_arg'

In [146]:
def my_func_optional(first_arg, second_arg="defaut value"):
    print(f"{first_arg = }\n{second_arg = }")

In [147]:
my_func_optional(first_arg=1)

first_arg = 1
second_arg = 'defaut value'


In [148]:
my_func_optional(1, "something else")

first_arg = 1
second_arg = 'something else'


# Imports

In [149]:
import math  # built-on module

In [150]:
math.pi

3.141592653589793

`math.cos` means using the `cos` function of the `math` library:

In [151]:
math.cos(math.pi)

-1.0

Importing functions from libraries allows to reuse existing stuff. Do not re-invent the wheel!

In [152]:
math.sqrt(math.cos(math.pi / 2) + math.sqrt(5))  # can be long 

1.4953487812212205

In [153]:
from math import sqrt, pi
sqrt(pi)  # instead of math.sqrt(math.pi))

1.7724538509055159

In [154]:
import numpy
from numpy import pi  # beware that names can be duplicated over packages!

In [155]:
numpy.linalg.norm(numpy.array([0, 1, 2]))

np.float64(2.23606797749979)

In [156]:
# we use aliases:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 

Respect conventions do *not* do:
```python
import numpy as yolo
import pandas as np
```

In [157]:
# more concise
np.linalg.norm(np.array([0, 1, 2]))

np.float64(2.23606797749979)